//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAJB_BS_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string jobType { get; set; }
        public string industry { get; set; }
        public string salaryMin { get; set; }
        public string salaryMax { get; set; }
        public System.DateTime jobDate { get; set; }
        public System.DateTime jobEndDate { get; set; }
        public bool active { get; set; }
        public Nullable<int> companyID { get; set; }
        public string applyTo { get; set; }
        public string reference { get; set; }
        public string experience { get; set; }
        public Nullable<int> views { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
