//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAJB_BS_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSearch
    {
        public int ID { get; set; }
        public string location { get; set; }
        public string radius { get; set; }
        public string industry { get; set; }
        public string jobType { get; set; }
        public string jobName { get; set; }
        public string companyName { get; set; }
        public string salaryMin { get; set; }
        public string salaryMax { get; set; }
        public string additionalLocations { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> najb_userID { get; set; }
        public bool active { get; set; }
        public string experience { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual NAJB_user NAJB_user { get; set; }
    }
}
